name: Format CI

on: [push, pull_request]

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Check code format
        run: |
          clang-format -n -Werror $(find -not -path "./build/*" -name "*.[ch]")
